#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef DAONNFCSDK_SWIFT_H
#define DAONNFCSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DaonNFCSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// A class representing a parsed Machine Readable Zone (MRZ) from identity documents.
/// Use this class to parse and access MRZ data from passports, ID cards, and similar documents.
SWIFT_CLASS("_TtC10DaonNFCSDK5IXMRZ")
@interface IXMRZ : NSObject
/// The first name(s) extracted from the MRZ, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
/// The last name(s) extracted from the MRZ, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
/// The gender extracted from the MRZ, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable gender;
/// The issuing state extracted from the MRZ, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable state;
/// The nationality extracted from the MRZ, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable nationality;
/// The personal number extracted from the MRZ, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable personalNumber;
/// The document code extracted from the MRZ, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable documentCode;
/// Whether the document is expired, as a string value.
@property (nonatomic, readonly, copy) NSString * _Nullable expired;
/// The date of birth extracted from the MRZ, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable dateOfBirth;
/// The date of expiry extracted from the MRZ, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable dateOfExpiry;
/// The document number extracted from the MRZ, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable documentNumber;
/// Initializes an IXMRZ instance by parsing the provided MRZ string.
/// \param mrz The MRZ string to parse.
///
///
/// throws:
/// <code>IXMRZ/ParseError</code> if the MRZ cannot be parsed.
- (nullable instancetype)initWithMrz:(NSString * _Nonnull)mrz error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// Returns a dictionary containing all parsed MRZ fields and their values.
///
/// returns:
/// A dictionary where the keys are MRZ field names and the values are the corresponding parsed values.
- (NSDictionary<NSString *, NSString *> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
/// Returns the number of parsed MRZ fields.
///
/// returns:
/// The count of parsed MRZ fields.
- (NSInteger)count SWIFT_WARN_UNUSED_RESULT;
/// Returns the value for a given MRZ field key.
/// \param string The key for the MRZ field.
///
///
/// returns:
/// The value for the field, or nil if not present.
- (NSString * _Nullable)getWithString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The type of document as determined from the MRZ.
typedef SWIFT_ENUM(NSInteger, DocumentType, open) {
/// Unknown document type.
  DocumentTypeUnknown = 0,
/// ID1 document type for credit card sized identity cards. Specifies a 3-line MRZ, 30 characters wide.
  DocumentTypeID1 = 1,
/// ID2 document type. Specifies a 2-line MRZ, 36 characters wide.
  DocumentTypeID2 = 2,
/// ID3 document type for passport booklets. Specifies a 2-line MRZ, 44 characters wide.
  DocumentTypeID3 = 3,
};

/// Recognizes and extracts Machine Readable Zone (MRZ) data from scanned text lines.
/// Use this class to process lines of text (typically from OCR or camera input) and extract valid MRZ strings for further parsing.
/// Sendable conformance: Mutable state (<code>line1</code>, <code>line2</code>, <code>line3</code>) is protected by a serial
/// DispatchQueue. Timer operations are dispatched to the main thread.
SWIFT_CLASS("_TtC10DaonNFCSDK15IXMRZRecognizer")
@interface IXMRZRecognizer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// <ul>
///   <li>
///     Cases:
///     <ul>
///       <li>
///         <code>bacThenPace</code>: Attempt BAC first; fall back to PACE if BAC fails.
///       </li>
///       <li>
///         <code>paceThenBac</code>: Attempt PACE (Password Authenticated Connection Establishment) first; fall back to BAC (Basic Access Control) if PACE fails.
///       </li>
///       <li>
///         <code>bacOnly</code>: Use only BAC for authentication. PACE will not be attempted.
///       </li>
///       <li>
///         <code>paceOnly</code>: Use only PACE for authentication. BAC will not be attempted.
///       </li>
///     </ul>
///   </li>
/// </ul>
typedef SWIFT_ENUM(NSInteger, IXNFCAuthenticationType, open) {
/// Attempt BAC first; fall back to PACE if BAC fails.
  IXNFCAuthenticationTypeBacThenPace = 0,
/// Attempt PACE first; fall back to BAC if PACE fails.
  IXNFCAuthenticationTypePaceThenBac = 1,
/// Use only BAC for authentication.
  IXNFCAuthenticationTypeBacOnly = 2,
/// Use only PACE for authentication.
  IXNFCAuthenticationTypePaceOnly = 3,
};

@class NSDate;
/// A utility class for converting and formatting <code>Date</code> objects and date strings for use with NFC passport data.
/// Provides static methods and constants for common date formats and conversions.
SWIFT_CLASS("_TtC10DaonNFCSDK15IXNFCDateParser")
@interface IXNFCDateParser : NSObject
/// The ISO 8601 date format: yyyy-MM-dd
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ISO8601Format;)
+ (NSString * _Nonnull)ISO8601Format SWIFT_WARN_UNUSED_RESULT;
/// The short date format: yyMMdd
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull shortDateFormat;)
+ (NSString * _Nonnull)shortDateFormat SWIFT_WARN_UNUSED_RESULT;
/// The long date format: yyyyMMdd
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull longDateFormat;)
+ (NSString * _Nonnull)longDateFormat SWIFT_WARN_UNUSED_RESULT;
/// Converts a string to a <code>Date</code> object.
/// \param from The string to convert. The string should be in either <code>shortDateFormat</code> or <code>longDateFormat</code>.
///
///
/// returns:
/// A <code>Date</code> object or <code>nil</code> if the conversion failed.
+ (NSDate * _Nullable)date:(NSString * _Nonnull)from SWIFT_WARN_UNUSED_RESULT;
/// Formats a date as a string.
/// \param from The date to format.
///
/// \param format The <code>DateFormatter</code> format. Default is <code>ISO8601Format</code>.
///
///
/// returns:
/// Formatted date or “NA” if the conversion failed.
+ (NSString * _Nonnull)string:(NSDate * _Nullable)from format:(NSString * _Nonnull)format SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// The default tag reader provider for NFC tags.
/// This class provides a default implementation of <code>IXNFCTagReaderProvider</code> that returns a tag reader for ISO 7816 tags (e.g., passports).
SWIFT_CLASS("_TtC10DaonNFCSDK29IXNFCDefaultTagReaderProvider")
@interface IXNFCDefaultTagReaderProvider : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents an issue encountered with NFC tag data.
/// Use this class to describe issues found during NFC tag reading, such as unsupported data groups or verification failures.
SWIFT_CLASS("_TtC10DaonNFCSDK10IXNFCIssue")
@interface IXNFCIssue : NSObject <NSCopying>
/// The issue identifier.
/// See <code>IXNFCPassportData</code> <code>tagDataIssueXXX</code> constants for possible values.
@property (nonatomic, readonly) NSInteger issue;
/// An optional detailed message describing the issue.
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
/// A string that represents the contents of the issue.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Class for passing parameters to the NFC Reader.
/// Use this class to set and retrieve parameters for NFC reading sessions, such as license, document numbers, dates, and other options.
SWIFT_CLASS("_TtC10DaonNFCSDK15IXNFCParameters")
@interface IXNFCParameters : NSObject
/// Create an IXNFCParameters without any initial parameters.
/// Initializes a new IXNFCParameters instance with no parameters set.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Create a IXNFCParameters instance from a dictionary.
/// The parameters can be set directly from the Document SDK OCR results.
/// Example:
/// \code
/// let params = IXNFCParameters(dictionary: _scanningResult.document.textExtracted)
///
/// \endcode\param dictionary A dictionary of keys and values.
///
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, NSString *> * _Nonnull)dictionary;
/// A string that represents the contents of the Parameters.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Get string parameter.
/// \param parameter The name of the parameter.
///
///
/// returns:
/// The parameter value or nil if the parameter has not been set.
- (id _Nullable)parameter:(NSString * _Nonnull)parameter SWIFT_WARN_UNUSED_RESULT;
/// Get boolean parameter.
/// \param parameter The name of the parameter.
///
///
/// returns:
/// The parameter value. Returns false if the parameter has not been set or cannot be converted to Bool.
- (BOOL)boolParameter:(NSString * _Nonnull)parameter SWIFT_WARN_UNUSED_RESULT;
/// Get byte array parameter.
/// \param parameter The name of the parameter.
///
///
/// returns:
/// The parameter value as a byte array, or nil if not set.
- (NSArray<NSNumber *> * _Nullable)stringParameter:(NSString * _Nonnull)parameter SWIFT_WARN_UNUSED_RESULT;
/// Set string parameter.
/// \param parameter The name of the parameter.
///
/// \param string The parameter value.
///
- (void)set:(NSString * _Nonnull)parameter string:(NSString * _Nonnull)string;
/// Set string parameter.
/// \param parameter The name of the parameter.
///
/// \param byteArray The parameter value.
///
- (void)set:(NSString * _Nonnull)parameter byteArray:(NSArray<NSNumber *> * _Nonnull)byteArray;
/// Set date parameter.
/// \param parameter The name of the parameter.
///
/// \param date The parameter value as a Date object.
///
- (void)set:(NSString * _Nonnull)parameter date:(NSDate * _Nonnull)date;
/// Set boolean parameter.
/// \param parameter The name of the parameter.
///
/// \param enable The parameter value.
///
- (void)set:(NSString * _Nonnull)parameter boolean:(BOOL)enable;
/// Set Integer parameter.
/// \param parameter The name of the parameter.
///
/// \param value The parameter value.
///
- (void)set:(NSString * _Nonnull)parameter int:(NSInteger)value;
/// Set parameters from an existing IXNFCParameters instance.
/// \param parameters The IXNFCParameters instance.
///
- (void)setWithParameters:(IXNFCParameters * _Nonnull)parameters;
/// Set parameters from a dictionary.
/// \param dictionary The dictionary of keys and values.
///
- (void)setWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
@end

/// Tag data interface.
/// Protocol for accessing parsed NFC tag data, including JSON representation, key-value pairs, and issues found during reading.
SWIFT_PROTOCOL("_TtP10DaonNFCSDK20IXNFCTagDataProtocol_")
@protocol IXNFCTagDataProtocol <NSObject>
/// Get a JSON representation of the data.
///
/// returns:
/// A JSON string.
- (NSString * _Nullable)json SWIFT_WARN_UNUSED_RESULT;
/// Check if any data was read.
///
/// returns:
/// True if there is no data.
- (BOOL)isEmpty SWIFT_WARN_UNUSED_RESULT;
/// Get all keys and values.
///
/// returns:
/// A map of data keys and values.
- (NSDictionary * _Nonnull)all SWIFT_WARN_UNUSED_RESULT;
/// Get issues found during reading.
///
/// returns:
/// A list of issues.
- (NSArray<IXNFCIssue *> * _Nonnull)issues SWIFT_WARN_UNUSED_RESULT;
@end

/// Tag data.
SWIFT_CLASS("_TtC10DaonNFCSDK12IXNFCTagData")
@interface IXNFCTagData : NSObject <IXNFCTagDataProtocol>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Indicates that the reader session is starting.
/// Use this constant when reporting that the NFC reader session is about to begin.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoInit;)
+ (NSInteger)tagDataInfoInit SWIFT_WARN_UNUSED_RESULT;
/// Indicates that the reader session is active.
/// Use this constant to report that the NFC reader session is currently scanning.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoScan;)
+ (NSInteger)tagDataInfoScan SWIFT_WARN_UNUSED_RESULT;
/// Indicates that reading from the tag has completed successfully.
/// Use this constant to report that the NFC data reading operation has finished successfully.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDone;)
+ (NSInteger)tagDataInfoDone SWIFT_WARN_UNUSED_RESULT;
/// Indicates that the process of reading data groups has begun
/// Use this constant to report the start of data reading.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoReadStarted;)
+ (NSInteger)tagDataInfoReadStarted SWIFT_WARN_UNUSED_RESULT;
/// Indicates that the connection with the tag was lost unexpectedly.
/// Use this constant to report disconnection events during an NFC session.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDisconnect;)
+ (NSInteger)tagDataInfoDisconnect SWIFT_WARN_UNUSED_RESULT;
/// Indicates that the connection with the tag has been resumed after a disconnection.
/// Use this constant to report that the NFC session has successfully reconnected to the tag.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoReconnect;)
+ (NSInteger)tagDataInfoReconnect SWIFT_WARN_UNUSED_RESULT;
/// Get a JSON representation of the data.
///
/// returns:
/// A JSON string
- (NSString * _Nullable)json SWIFT_WARN_UNUSED_RESULT;
/// Check if any data was read.
///
/// returns:
/// True if there is no data.
- (BOOL)isEmpty SWIFT_WARN_UNUSED_RESULT;
/// Get all keys and values.
///
/// returns:
/// A map of data keys and values.
- (NSDictionary * _Nonnull)all SWIFT_WARN_UNUSED_RESULT;
/// Get issues found during reading.
///
/// returns:
/// A list of issues.
- (NSArray<IXNFCIssue *> * _Nonnull)issues SWIFT_WARN_UNUSED_RESULT;
@end

@class UIImage;
@class X509Certificate;
/// Passport data for ICAO-compliant documents.
/// This class provides access to parsed data groups and fields from an electronic passport (eMRTD).
/// ICAO data groups:
/// \code
///    Data Group 1    Machine Readable Zone (Required)
///    Data Group 2    Face (Required)
///    Data Group 3    Fingerprint (Optional)
///    Data Group 4    Iris (Optional)
///    Data Group 5    Displayed portrait (Optional)
///    Data Group 6    Reserved for future use
///    Data Group 7    Displayed signature (Optional)
///    Data Group 8    Data features (Optional)
///    Data Group 9    Structure features (Optional)
///    Data Group 10   Substance features (Optional)
///    Data Group 11   Additional personal details (Optional)
///    Data Group 12   Additional document features (Optional)
///    Data Group 13   Optional details (Optional)
///    Data Group 14   Security options (Conditional)
///    Data Group 15   Active Authentication publickey info (Conditional)
///    Data Group 16   Persons to notify (Optional)
///
/// \endcode
SWIFT_CLASS("_TtC10DaonNFCSDK17IXNFCPassportData")
@interface IXNFCPassportData : IXNFCTagData
/// Data Group 1 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG1;)
+ (NSInteger)tagDataInfoDG1 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 1 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG1Success;)
+ (NSInteger)tagDataInfoDG1Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 1 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG1Fail;)
+ (NSInteger)tagDataInfoDG1Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 2 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG2;)
+ (NSInteger)tagDataInfoDG2 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 2 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG2Success;)
+ (NSInteger)tagDataInfoDG2Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 2 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG2Fail;)
+ (NSInteger)tagDataInfoDG2Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 3 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG3;)
+ (NSInteger)tagDataInfoDG3 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 3 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG3Success;)
+ (NSInteger)tagDataInfoDG3Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 3 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG3Fail;)
+ (NSInteger)tagDataInfoDG3Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 4 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG4;)
+ (NSInteger)tagDataInfoDG4 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 4 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG4Success;)
+ (NSInteger)tagDataInfoDG4Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 4 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG4Fail;)
+ (NSInteger)tagDataInfoDG4Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 5 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG5;)
+ (NSInteger)tagDataInfoDG5 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 5 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG5Success;)
+ (NSInteger)tagDataInfoDG5Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 5 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG5Fail;)
+ (NSInteger)tagDataInfoDG5Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 6 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG6;)
+ (NSInteger)tagDataInfoDG6 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 6 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG6Success;)
+ (NSInteger)tagDataInfoDG6Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 6 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG6Fail;)
+ (NSInteger)tagDataInfoDG6Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 7 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG7;)
+ (NSInteger)tagDataInfoDG7 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 7 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG7Success;)
+ (NSInteger)tagDataInfoDG7Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 7 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG7Fail;)
+ (NSInteger)tagDataInfoDG7Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 8 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG8;)
+ (NSInteger)tagDataInfoDG8 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 8 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG8Success;)
+ (NSInteger)tagDataInfoDG8Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 8 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG8Fail;)
+ (NSInteger)tagDataInfoDG8Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 9 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG9;)
+ (NSInteger)tagDataInfoDG9 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 9 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG9Success;)
+ (NSInteger)tagDataInfoDG9Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 9 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG9Fail;)
+ (NSInteger)tagDataInfoDG9Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 10 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG10;)
+ (NSInteger)tagDataInfoDG10 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 10 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG10Success;)
+ (NSInteger)tagDataInfoDG10Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 10 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG10Fail;)
+ (NSInteger)tagDataInfoDG10Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 11 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG11;)
+ (NSInteger)tagDataInfoDG11 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 11 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG11Success;)
+ (NSInteger)tagDataInfoDG11Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 11 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG11Fail;)
+ (NSInteger)tagDataInfoDG11Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 12 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG12;)
+ (NSInteger)tagDataInfoDG12 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 12 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG12Success;)
+ (NSInteger)tagDataInfoDG12Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 12 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG12Fail;)
+ (NSInteger)tagDataInfoDG12Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 13 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG13;)
+ (NSInteger)tagDataInfoDG13 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 13 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG13Success;)
+ (NSInteger)tagDataInfoDG13Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 13 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG13Fail;)
+ (NSInteger)tagDataInfoDG13Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 14 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG14;)
+ (NSInteger)tagDataInfoDG14 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 14 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG14Success;)
+ (NSInteger)tagDataInfoDG14Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 14 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG14Fail;)
+ (NSInteger)tagDataInfoDG14Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 15 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG15;)
+ (NSInteger)tagDataInfoDG15 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 15 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG15Success;)
+ (NSInteger)tagDataInfoDG15Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 15 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG15Fail;)
+ (NSInteger)tagDataInfoDG15Fail SWIFT_WARN_UNUSED_RESULT;
/// Data Group 16 is being read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG16;)
+ (NSInteger)tagDataInfoDG16 SWIFT_WARN_UNUSED_RESULT;
/// Data Group 16 completed read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG16Success;)
+ (NSInteger)tagDataInfoDG16Success SWIFT_WARN_UNUSED_RESULT;
/// Data Group 16 failed to read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDG16Fail;)
+ (NSInteger)tagDataInfoDG16Fail SWIFT_WARN_UNUSED_RESULT;
/// Reading Card Access information.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoCardAccess;)
+ (NSInteger)tagDataInfoCardAccess SWIFT_WARN_UNUSED_RESULT;
/// Reading Card Access information was successful.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoCardAccessSuccess;)
+ (NSInteger)tagDataInfoCardAccessSuccess SWIFT_WARN_UNUSED_RESULT;
/// Reading Card Access information failed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoCardAccessFail;)
+ (NSInteger)tagDataInfoCardAccessFail SWIFT_WARN_UNUSED_RESULT;
/// Reading security information.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoSOD;)
+ (NSInteger)tagDataInfoSOD SWIFT_WARN_UNUSED_RESULT;
/// Reading security information was successful.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoSODSuccess;)
+ (NSInteger)tagDataInfoSODSuccess SWIFT_WARN_UNUSED_RESULT;
/// Reading security information failed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoSODFail;)
+ (NSInteger)tagDataInfoSODFail SWIFT_WARN_UNUSED_RESULT;
/// Reading group information.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoCOM;)
+ (NSInteger)tagDataInfoCOM SWIFT_WARN_UNUSED_RESULT;
/// Reading available data groups.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoCOMFileList;)
+ (NSInteger)tagDataInfoCOMFileList SWIFT_WARN_UNUSED_RESULT;
/// Reading group information was successful.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoCOMSuccess;)
+ (NSInteger)tagDataInfoCOMSuccess SWIFT_WARN_UNUSED_RESULT;
/// Reading group information failed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoCOMFail;)
+ (NSInteger)tagDataInfoCOMFail SWIFT_WARN_UNUSED_RESULT;
/// Processing PACE data
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoPACE;)
+ (NSInteger)tagDataInfoPACE SWIFT_WARN_UNUSED_RESULT;
/// Processing PACE data was successful.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoPACESuccess;)
+ (NSInteger)tagDataInfoPACESuccess SWIFT_WARN_UNUSED_RESULT;
/// Processing PACE data failed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoPACEFail;)
+ (NSInteger)tagDataInfoPACEFail SWIFT_WARN_UNUSED_RESULT;
/// Processing PACE is not supported by the passport.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoPACENotSupported;)
+ (NSInteger)tagDataInfoPACENotSupported SWIFT_WARN_UNUSED_RESULT;
/// Processing Basic Access.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoBAC;)
+ (NSInteger)tagDataInfoBAC SWIFT_WARN_UNUSED_RESULT;
/// Processing Basic Access was successful.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoBACSuccess;)
+ (NSInteger)tagDataInfoBACSuccess SWIFT_WARN_UNUSED_RESULT;
/// Processing Basic Access failed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoBACFail;)
+ (NSInteger)tagDataInfoBACFail SWIFT_WARN_UNUSED_RESULT;
/// License check.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoLicenseCheck;)
+ (NSInteger)tagDataInfoLicenseCheck SWIFT_WARN_UNUSED_RESULT;
/// License check was successful.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoLicenseCheckSuccess;)
+ (NSInteger)tagDataInfoLicenseCheckSuccess SWIFT_WARN_UNUSED_RESULT;
/// License check failed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoLicenseCheckFail;)
+ (NSInteger)tagDataInfoLicenseCheckFail SWIFT_WARN_UNUSED_RESULT;
/// Active authentication verification.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoAA;)
+ (NSInteger)tagDataInfoAA SWIFT_WARN_UNUSED_RESULT;
/// Active authentication no data.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoAANoData;)
+ (NSInteger)tagDataInfoAANoData SWIFT_WARN_UNUSED_RESULT;
/// Active authentication no challenge.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoAANoChallenge;)
+ (NSInteger)tagDataInfoAANoChallenge SWIFT_WARN_UNUSED_RESULT;
/// Active authentication verification was successful.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoAAVerified;)
+ (NSInteger)tagDataInfoAAVerified SWIFT_WARN_UNUSED_RESULT;
/// Active authentication verification failed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoAANotVerified;)
+ (NSInteger)tagDataInfoAANotVerified SWIFT_WARN_UNUSED_RESULT;
/// DSC verification.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDSC;)
+ (NSInteger)tagDataInfoDSC SWIFT_WARN_UNUSED_RESULT;
/// DSC verification was successful.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDSCVerified;)
+ (NSInteger)tagDataInfoDSCVerified SWIFT_WARN_UNUSED_RESULT;
/// DSC verification failed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDSCNotVerified;)
+ (NSInteger)tagDataInfoDSCNotVerified SWIFT_WARN_UNUSED_RESULT;
/// Issue: Data group hash is invalid.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataIssueDataGroupHashInvalid;)
+ (NSInteger)tagDataIssueDataGroupHashInvalid SWIFT_WARN_UNUSED_RESULT;
/// Issue: Data group is unsupported.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataIssueDataGroupUnsupported;)
+ (NSInteger)tagDataIssueDataGroupUnsupported SWIFT_WARN_UNUSED_RESULT;
/// Issue: Data group was not read.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataIssueDataGroupNotRead;)
+ (NSInteger)tagDataIssueDataGroupNotRead SWIFT_WARN_UNUSED_RESULT;
/// Issue: CSCA verification failed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataIssueCSCAVerifyFailed;)
+ (NSInteger)tagDataIssueCSCAVerifyFailed SWIFT_WARN_UNUSED_RESULT;
/// Issue: DSC signature failed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataIssueDSCSignatureFailed;)
+ (NSInteger)tagDataIssueDSCSignatureFailed SWIFT_WARN_UNUSED_RESULT;
/// Device info (model, make, etc…)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDevice;)
+ (NSInteger)tagDataInfoDevice SWIFT_WARN_UNUSED_RESULT;
/// NFC reader configuration info (photo reading enabled, raw data enabled, etc…)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoReaderConfiguration;)
+ (NSInteger)tagDataInfoReaderConfiguration SWIFT_WARN_UNUSED_RESULT;
/// Issue: No data read from chip.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoNoData;)
+ (NSInteger)tagDataInfoNoData SWIFT_WARN_UNUSED_RESULT;
/// Digest algorithm info.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoDigestAlgorithm;)
+ (NSInteger)tagDataInfoDigestAlgorithm SWIFT_WARN_UNUSED_RESULT;
/// Signature digest algorithm info.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoSignatureDigestAlgorithm;)
+ (NSInteger)tagDataInfoSignatureDigestAlgorithm SWIFT_WARN_UNUSED_RESULT;
/// Signature algorithm info.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagDataInfoSignatureAlgorithm;)
+ (NSInteger)tagDataInfoSignatureAlgorithm SWIFT_WARN_UNUSED_RESULT;
/// A string that represents the contents of the data.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Get MRZ string.
@property (nonatomic, readonly, copy) NSString * _Nullable mrz;
/// Get the address (if available).
@property (nonatomic, readonly, copy) NSString * _Nullable address;
/// Get place of birth (if available).
@property (nonatomic, readonly, copy) NSString * _Nullable placeOfBirth;
/// Get addtional document numbers (if available).
@property (nonatomic, readonly, copy) NSString * _Nullable documentNumbers;
/// Get given names.
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
/// Get last/family name.
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
/// Get gender.
@property (nonatomic, readonly, copy) NSString * _Nullable gender;
/// Get issuing state or country.
@property (nonatomic, readonly, copy) NSString * _Nullable state;
/// Get nationality.
@property (nonatomic, readonly, copy) NSString * _Nullable nationality;
/// Get date of birth.
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfBirth;
/// Get document expiry date.
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfExpiry;
/// Get document issue date (if available).
@property (nonatomic, readonly, copy) NSDate * _Nullable dateOfIssue;
/// Get document number.
@property (nonatomic, readonly, copy) NSString * _Nullable documentNumber;
/// Get personal number.
@property (nonatomic, readonly, copy) NSString * _Nullable personalNumber;
/// Get document code P, I, A or C.
@property (nonatomic, readonly, copy) NSString * _Nullable documentCode;
/// Get issuing authority.
@property (nonatomic, readonly, copy) NSString * _Nullable issuingAuthority;
/// Get photo (requires that photo reading is enabled).
@property (nonatomic, readonly, strong) UIImage * _Nullable photo;
/// Get the Document Signing Certificate.
@property (nonatomic, readonly, strong) X509Certificate * _Nullable certificate;
/// Check if the document is expired.
@property (nonatomic, readonly) BOOL isExpired;
/// Check if the Document Signing Certificate was verified with a CSCA certificate.
/// The certificate needs to be provided in the parameters to the NFC reader using the 3 letter ISO country code
/// and a base64 encoded certificate.
/// \code
///     params.set("DNK", base64EncodedCSCA)
///
/// \endcode
@property (nonatomic, readonly) BOOL isCertificateVerified;
/// Get a JSON representation of the data.
///
/// returns:
/// A JSON string.
- (NSString * _Nullable)json SWIFT_WARN_UNUSED_RESULT;
/// Check if any data was read.
///
/// returns:
/// True if there is no data.
- (BOOL)isEmpty SWIFT_WARN_UNUSED_RESULT;
/// Get all keys and values.
///
/// returns:
/// A map of data keys and values.
- (NSDictionary * _Nonnull)all SWIFT_WARN_UNUSED_RESULT;
/// Get issues found during reading.
///
/// returns:
/// A list of issues.
- (NSArray<IXNFCIssue *> * _Nonnull)issues SWIFT_WARN_UNUSED_RESULT;
/// Verify the stored Document Signer Certificate (DSC).
/// The DSC must be validated against the Country Signing Certification Authority (CSCA) to
/// validate the digital signature.
/// \param csca A Base64 encoded CSCA certificate.
///
///
/// returns:
/// The result of the verification.
- (BOOL)verify:(NSString * _Nonnull)csca SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// Class for passing parameters to the NFC Reader for reading a travel document.
/// Use this class to set and retrieve parameters for NFC reading sessions specific to travel documents, such as document number, date of birth, and date of expiry. Supports initialization from MRZ string or explicit BAC/PACE data.
SWIFT_CLASS("_TtC10DaonNFCSDK23IXNFCPassportParameters")
@interface IXNFCPassportParameters : IXNFCParameters
/// Document Number parameter name.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull documentNumber;)
+ (NSString * _Nonnull)documentNumber SWIFT_WARN_UNUSED_RESULT;
/// Date of Birth parameter name.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dateOfBirth;)
+ (NSString * _Nonnull)dateOfBirth SWIFT_WARN_UNUSED_RESULT;
/// Date of Expiry parameter name.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dateOfExpiry;)
+ (NSString * _Nonnull)dateOfExpiry SWIFT_WARN_UNUSED_RESULT;
/// Create a Parameter object.
/// Use the individual setter methods to set a parameter.
/// \code
/// // Add country certificate
/// params.set("DNK", CSCA.DNK)
///
/// // Set document number
/// params.set(PassportParameters.DOCUMENT_NUMBER, "555")
///
/// \endcode
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Create a IXNFCPassportParameters instance from an MRZ string.
/// Supported formats:
/// <ul>
///   <li>
///     ID1 document type for credit card sized identity cards. Specifies a 3-line MRZ, 30 characters wide.
///   </li>
///   <li>
///     ID3 document type for passport booklets. Specifies a 2-line MRZ, 44 characters wide.
///   </li>
/// </ul>
/// The MRZ can contain new line characters.
/// \code
/// let mrz = "P<DNKERIKSSEN<<ANNA<MARIA<<<<<<<<<<<<<<<<<<<\nL897902C36UTO7408122F1204159ZE184226B<<<<<10"
/// let params = IXNFCParameters(mrz: mrz)
///
/// \endcode\param mrz An MRZ string.
///
///
/// throws:
/// <code>IXNFCPassportParameters/ParametersError</code> if required BAC data is missing.
- (nullable instancetype)initWithMrz:(NSString * _Nonnull)mrz error:(NSError * _Nullable * _Nullable)error;
/// Create a IXNFCPassportParameters instance with required BAC/PACE access information.
/// \param documentNumber The passport document number.
///
/// \param dateOfBirth The date of birth stated on the passport.
///
/// \param dateOfExpiry The passport expiry date.
///
- (nonnull instancetype)initWithDocumentNumber:(NSString * _Nonnull)documentNumber dateOfBirth:(NSDate * _Nonnull)dateOfBirth dateOfExpiry:(NSDate * _Nonnull)dateOfExpiry;
/// Enable photo reading.
/// \param photo If true, read the stored photo.
///
- (void)enablePhoto:(BOOL)photo;
/// Provide the raw EF data.
/// Includes the raw EF group data in the result. The data is base64 encoded.
/// \param data If true, data will include the raw EF group data.
///
- (void)enableRawData:(BOOL)data;
- (void)enablePACEAuthenticationWithEnabled:(BOOL)enabled SWIFT_DEPRECATED_MSG("Use setAuthenticationType() instead.");
/// Sets the authentication type to use when reading a passport via NFC.
/// note:
/// If not explicitly set, the default authentication type is <code>IXNFCAuthenticationType/paceThenBac</code>.
/// \param type The authentication type to use. See <code>IXNFCAuthenticationType</code> for options.
///
- (void)setAuthenticationType:(enum IXNFCAuthenticationType)type;
/// Provide challenge retrieved from the server for active authentication purpose.
/// \param challenge [UInt8] representation of the challenge.
///
- (void)setChallenge:(NSArray<NSNumber *> * _Nonnull)challenge;
@end

@protocol IXNFCReaderDelegate;
/// The NFC reader object handles tag reading and parsing.
/// Example usage:
/// \code
/// let reader = IXNFCReader(license: "license")
/// let params = IXNFCPassportParameters(
///     documentNumber: _passportNumberTextField.text,
///     dateOfBirth: _dateOfBirthPicker.date,
///     expiryDate: _expiryDatePicker.date)
/// // Set optional Country CA, e.g for Denmark (DNK) and USA
/// params.set(parameter:"DNK", string:DNK)
/// params.set(parameter:"USA", string:USA)
/// // Read photo
/// params.set(photo: true)
/// // Set IXNFCReaderDelegate
/// reader?.delegate = self
/// reader?.read(parameters: params, completion: { (data, error) in
///     print("Data: ", data?.all())
///     print("Issues: ", data?.issues())
///     print("JSON: ", data?.json())
///     if let passport = data as? IXNFCPassportData {
///         let nationality = passport.nationality
///         // Verify DSC against CSCA
///         let verified = passport.verify(csca:CSCA)
///     }
/// })
///
/// \endcode
SWIFT_CLASS("_TtC10DaonNFCSDK11IXNFCReader")
@interface IXNFCReader : NSObject
/// If a custom or default error message is desired, it can be set using this parameter. Otherwise, if left unset, the SDK will return an error message obtained from the <code>error.localizedDescription</code> property.
@property (nonatomic, copy) NSString * _Nullable nfcDialogueErrorMessageText;
/// The object that acts as the delegate of the IXNFCReader.
@property (nonatomic, weak) id <IXNFCReaderDelegate> _Nullable delegate;
/// Get SDK version
///
/// returns:
/// Returns the SDK version
- (NSString * _Nonnull)version SWIFT_WARN_UNUSED_RESULT;
/// Creates an IXNFCReader using the specified license.
/// \param license License string or path to license file.
///
- (nonnull instancetype)initWithLicense:(NSString * _Nonnull)license OBJC_DESIGNATED_INITIALIZER;
/// Check if NFC is supported.
///
/// returns:
/// true if NFC is supported by this device.
+ (BOOL)isSupported SWIFT_WARN_UNUSED_RESULT;
/// Get SDK version
///
/// returns:
/// Returns the SDK version
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// Read NFC tag.
/// \param parameters Reading options and document parameters. For passports MRZ data or BAC/PACE access data is required, e.g. document number, date of birth and date of expiry.
///
/// \param completion The completion block.
///
/// \param data The IXNFCTagData object with the NFC tag data.
///
/// \param error An NSError if an error occured.
///
- (void)readWithParameters:(IXNFCParameters * _Nullable)parameters completion:(void (^ _Nonnull)(IXNFCTagData * _Nullable, NSError * _Nullable))completion;
/// Force cancel session programmatically and dismiss NFC dialogue.
/// \param message custom message text on dialogue
///
- (void)stopWithErrorMessage:(NSString * _Nonnull)message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class IXNFCTagReaderInfo;
/// The IXNFCTagReaderDelegate is implemented by the tag reader and is intended for
/// adding additional readers to the SDK.
/// The Tag Reader will call this delegate to update the UI and provide information to the IXNFCReader.
/// Override with caution.
SWIFT_PROTOCOL("_TtP10DaonNFCSDK22IXNFCTagReaderDelegate_")
@protocol IXNFCTagReaderDelegate
/// Called when the tag was read successfully.
/// \param data The IXNFCTagData object containing the parsed NFC tag data.
///
- (void)tagReaderDidFinishWithData:(IXNFCTagData * _Nonnull)data;
/// Called if an error occurred.
/// \param error An NSError object describing the error.
///
- (void)tagReaderFailedWithError:(NSError * _Nullable)error;
/// Called during reading with status information.
/// \param info The IXNFCTagReaderInfo object containing status and progress information.
///
- (void)tagReaderInformationWithInfo:(IXNFCTagReaderInfo * _Nonnull)info;
@optional
/// Called when the analytics data should be emitted.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     name: The name of the event to be emitted.
///   </li>
///   <li>
///     analyticsData: The String representation of analytics data to be emitted.
///   </li>
/// </ul>
- (void)onAnalyticsDataReady:(NSString * _Nonnull)name :(NSString * _Nullable)analyticsData;
@end

@interface IXNFCReader (SWIFT_EXTENSION(DaonNFCSDK)) <IXNFCTagReaderDelegate>
- (void)tagReaderDidFinishWithData:(IXNFCTagData * _Nonnull)data;
- (void)tagReaderFailedWithError:(NSError * _Nullable)error;
- (void)tagReaderInformationWithInfo:(IXNFCTagReaderInfo * _Nonnull)info;
- (void)onAnalyticsDataReady:(NSString * _Nonnull)code :(NSString * _Nullable)data;
@end

/// Provides real-time feedback on the status of the NFC reader session.
SWIFT_PROTOCOL("_TtP10DaonNFCSDK19IXNFCReaderDelegate_")
@protocol IXNFCReaderDelegate
/// Called when the tag reader are about to update the string displayed to the user.
/// \param info A IXNFCTagReaderInfo object containing the current status and progress.
///
///
/// returns:
/// Message to display to the user.
- (NSString * _Nullable)readerDidUpdateWithInfo:(IXNFCTagReaderInfo * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
@optional
/// Called when the analytics data should be emitted.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     name: The name of the event to be emitted.
///   </li>
///   <li>
///     analyticsData: The String representation of analytics data to be emitted.
///   </li>
/// </ul>
- (void)onAnalyticsDataReady:(NSString * _Nonnull)name :(NSString * _Nullable)analyticsData;
@end

@interface IXNFCTagData (SWIFT_EXTENSION(DaonNFCSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// Protocol for reading NFC tags.
/// Implement this protocol to provide custom NFC tag reading logic. The <code>read</code> method is called with parameters and a delegate for reporting progress and results.
SWIFT_PROTOCOL("_TtP10DaonNFCSDK14IXNFCTagReader_")
@protocol IXNFCTagReader
/// Reads an NFC tag with the specified parameters and delegate.
/// \param parameters The parameters for the NFC reading session.
///
/// \param delegate The delegate to receive reading events and results.
///
- (void)readWithParameters:(IXNFCParameters * _Nonnull)parameters delegate:(id <IXNFCTagReaderDelegate> _Nullable)delegate;
@end

/// A class that represents the data read from an NFC tag.
SWIFT_CLASS("_TtC10DaonNFCSDK18IXNFCTagReaderData")
@interface IXNFCTagReaderData : IXNFCTagData
/// A string that represents the contents of the data.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Gets a string value for a given key.
/// \param key The key for the value.
///
///
/// returns:
/// The string value, or nil if not present.
- (NSString * _Nullable)getWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
/// Gets a boolean value for a given key.
/// \param key The key for the value.
///
///
/// returns:
/// The boolean value, or false if not present or not convertible.
- (BOOL)getBoolWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
/// Gets a date value for a given key.
/// \param key The key for the value.
///
///
/// returns:
/// The date value, or nil if not present or not convertible.
- (NSDate * _Nullable)getDateWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
/// Gets an image for a given key.
/// \param key The key for the image.
///
///
/// returns:
/// The UIImage, or nil if not present or not convertible.
- (UIImage * _Nullable)getImageWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
/// Returns all key-value pairs as an NSDictionary.
///
/// returns:
/// An NSDictionary containing all data.
- (NSDictionary * _Nonnull)all SWIFT_WARN_UNUSED_RESULT;
/// Returns a JSON representation of the data.
///
/// returns:
/// A JSON string, or nil if serialization fails.
- (NSString * _Nullable)json SWIFT_WARN_UNUSED_RESULT;
/// Returns true if the data is empty.
///
/// returns:
/// True if empty, false otherwise.
- (BOOL)isEmpty SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// The IXNFCTagReaderInfo object is returned by the <code>IXNFCReaderDelegate</code> and <code>IXNFCTagReaderDelegate</code> with information and progress during reading of a tag.
SWIFT_CLASS("_TtC10DaonNFCSDK18IXNFCTagReaderInfo")
@interface IXNFCTagReaderInfo : NSObject
/// Info code indicating the current operation or status.
/// See <code>IXNFCPassportData</code> and <code>IXNFCTagData</code> <code>tagDataInfoXXX</code> constants for possible values.
@property (nonatomic, readonly) NSInteger code;
/// An optional message describing the current status or operation.
@property (nonatomic, readonly, copy) NSString * _Nullable message;
/// Progress percentage (0..100) indicating how much of the tag reading process is complete.
@property (nonatomic, readonly) NSInteger percent;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSData;
@class NSNumber;
@class X509PublicKey;
SWIFT_CLASS("_TtC10DaonNFCSDK15X509Certificate")
@interface X509Certificate : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSData * _Nullable encoded;
/// Checks that the given date is within the certificate’s validity period.
- (BOOL)checkValidity:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
/// Gets the serialNumber value from the certificate.
@property (nonatomic, readonly, strong) NSNumber * _Nullable serialNumber;
/// Returns the issuer (issuer distinguished name) value from the certificate as a String.
@property (nonatomic, readonly, copy) NSString * _Nullable issuerDistinguishedName;
/// Returns the subject (subject distinguished name) value from the certificate as a String.
@property (nonatomic, readonly, copy) NSString * _Nullable subjectDistinguishedName;
/// Gets the notBefore date from the validity period of the certificate.
@property (nonatomic, readonly, copy) NSDate * _Nullable notBefore;
/// Gets the notAfter date from the validity period of the certificate.
@property (nonatomic, readonly, copy) NSDate * _Nullable notAfter;
/// Gets the signature value (the raw signature bits) from the certificate.
@property (nonatomic, readonly, copy) NSData * _Nullable signature;
/// Gets the signature algorithm name for the certificate signature algorithm.
@property (nonatomic, readonly, copy) NSString * _Nullable sigAlgName;
/// Gets the informations of the public key from this certificate.
@property (nonatomic, readonly, strong) X509PublicKey * _Nullable publicKey;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10DaonNFCSDK13X509PublicKey")
@interface X509PublicKey : NSObject
@property (nonatomic, readonly, copy) NSData * _Nullable key;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
