#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef DAONTRUSTSDK_SWIFT_H
#define DAONTRUSTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DaonTrustSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// A FIDO credential representing a registered authenticator.
/// Example JSON representation:
/// \code
/// {
///   "name": "silent",
///   "aaid": "D409#2601",
///   "keyid": "4c2b3ea0-cc3f-4b60-8588-207fd53608f2",
///   "created": 1751037260645,
///   "username": "jonny"
/// }
///
/// \endcode
SWIFT_CLASS("_TtC12DaonTrustSDK10Credential")
@interface Credential : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Configuration parameters for a device intelligence operation.
SWIFT_CLASS("_TtC12DaonTrustSDK12DIParameters")
@interface DIParameters : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@class Parameters;
/// The <code>DaonAppkeysProcessorModule</code> protocol defines a contract whereby an object that implements it can be used
/// to perform FIDO/UAF authentication, registration, and credential management.
SWIFT_PROTOCOL("_TtP12DaonTrustSDK26DaonAppkeysProcessorModule_")
@protocol DaonAppkeysProcessorModule
/// Returns the FIDO application identifier for the current session.
- (NSString * _Nonnull)appId SWIFT_WARN_UNUSED_RESULT;
/// Returns whether the required FIDO frameworks (DaonFIDOSDK, DaonCryptoSDK, DaonAuthenticatorSDK) are available at runtime.
- (BOOL)isAvailable SWIFT_WARN_UNUSED_RESULT;
/// Returns whether biometric authentication (Touch ID or Face ID) is supported and enabled on this device.
- (BOOL)isBiometricsSupported SWIFT_WARN_UNUSED_RESULT;
/// Returns the version string of the underlying FIDO SDK.
- (NSString * _Nonnull)version SWIFT_WARN_UNUSED_RESULT;
/// Retrieves the list of registered FIDO credentials as a base64-encoded JSON string.
/// \param completion A closure called with the base64-encoded credential JSON on success, or an <code>Error</code> on failure.
///
- (void)credentialsWithCompletion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Performs a FIDO registration operation using the provided parameters.
/// \param parameters A <code>Parameters</code> instance containing the base64-encoded FIDO message and optional configuration.
///
/// \param completion A closure called with the base64-encoded registration response on success, or an <code>Error</code> on failure.
///
- (void)registerWithParameters:(Parameters * _Nonnull)parameters completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Performs a FIDO authentication operation using the provided parameters.
/// \param parameters A <code>Parameters</code> instance containing the base64-encoded FIDO message and optional configuration.
///
/// \param completion A closure called with the base64-encoded authentication response on success, or an <code>Error</code> on failure.
///
- (void)authenticateWithParameters:(Parameters * _Nonnull)parameters completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Deregisters one or more FIDO authenticators.
/// \param parameters A <code>Parameters</code> instance containing a base64-encoded FIDO deregistration message, or a name such as <code>"ALL"</code>, <code>"BIOMETRIC"</code>, or <code>"DEVICE"</code>.
///
/// \param completion A closure called with the base64-encoded result on success, or an <code>Error</code> on failure.
///
- (void)deregisterWithParameters:(Parameters * _Nonnull)parameters completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Sends a FIDO notification with the provided parameters.
/// \param parameters A <code>Parameters</code> instance containing the base64-encoded FIDO notification message.
///
/// \param completion A closure called with the base64-encoded result on success, or an <code>Error</code> on failure.
///
- (void)notifyWithParameters:(Parameters * _Nonnull)parameters completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Cancels any ongoing operations.
/// \param message The message to provide to the user when cancelling any NFC scanning UI. Or nil if no message is required.
///
- (void)cancelWithMessage:(NSString * _Nullable)message;
/// Releases any resources held by the processor module.
/// After calling this method, the module cannot be used again.
- (void)close;
@end

/// The <code>DaonDeviceIntegrityProcessorModule</code> protocol defines a contract for performing
/// device intelligence operations using a device fingerprinting service.
SWIFT_PROTOCOL("_TtP12DaonTrustSDK34DaonDeviceIntegrityProcessorModule_")
@protocol DaonDeviceIntegrityProcessorModule
/// Returns whether the device intelligence framework is available at runtime.
///
/// returns:
/// <code>true</code> if the required framework is linked and loaded; otherwise <code>false</code>.
- (BOOL)isAvailable SWIFT_WARN_UNUSED_RESULT;
/// Returns the version string of the underlying device intelligence SDK.
- (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
/// Returns the list of supported capability identifiers (e.g. <code>"SIGNALS"</code>).
- (NSArray<NSString *> * _Nonnull)getCapabilities SWIFT_WARN_UNUSED_RESULT;
/// Performs a device fingerprint operation and returns the result asynchronously.
/// \param parameters A <code>DIParameters</code> instance containing the API key, region, and optional endpoint.
///
/// \param completion A closure called with a base64-encoded sealed result on success, or an <code>Error</code> on failure.
///
- (void)processOperationWithParameters:(DIParameters * _Nonnull)parameters completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Releases any resources held by the processor. The module should not be used after calling this method.
- (void)close;
@end

@class DaonDocumentProcessorResult;
/// The <code>DaonDocumentProcessorModule</code> protocol defines a contract whereby an object that implements it can be used to perform
/// MRZ Image OCR and NFC Scanning.
SWIFT_PROTOCOL("_TtP12DaonTrustSDK27DaonDocumentProcessorModule_")
@protocol DaonDocumentProcessorModule
/// Determines whether NFC scanning is supported with the current device and operating system configuration.
///
/// returns:
/// <code>true</code> if NFC scanning is supported, <code>false</code> otherwise.
- (BOOL)isNfcSupported SWIFT_WARN_UNUSED_RESULT;
/// Performs MRZ OCR on the provided image.
/// \param image The base64 encoded image to perform MRZ OCR on.
///
/// \param onCompletion The completion handler to call when the MRZ OCR operation is complete. Providing whether the MRZ is valid and the MRZ string.
///
- (void)performMrzOcrWithImage:(NSString * _Nonnull)base64String onCompletion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))onCompletion;
/// Performs NFC scanning using the provided mrz string.
/// \param mrzString The MRZ string to be used for BAC or PACE access control.
///
/// \param challenge The challenge to use for NFC scanning. Or nil if no challenge is required.
///
/// \param authenticationType The authentication type to use with the NFC document. Or nil if the default (BAC then PACE) is acceptable.
///
/// \param onCompletion The completion handler to call when the NFC scanning operation is complete. Providing any errors that occurred and the NFC scanning result.
///
- (void)performNfcScanWithMrzString:(NSString * _Nonnull)mrzString challenge:(NSArray<NSNumber *> * _Nullable)challenge authenticationType:(NSString * _Nullable)authenticationType onCompletion:(void (^ _Nonnull)(NSError * _Nullable, DaonDocumentProcessorResult * _Nullable))onCompletion;
/// Performs NFC scanning using the provided bac access control parameters.
/// \param docummentNumber BAC document number.
///
/// \param dateOfBirth BAC document date of birth. Using the “yyMMdd” format.
///
/// \param dateOfExpiry BAC document date of expiration. Using the “yyMMdd” format.
///
/// \param challenge The challenge to use for NFC scanning. Or nil if no challenge is required.
///
/// \param authenticationType The authentication type to use with the NFC document. Or nil if the default (BAC then PACE) is acceptable.
///
/// \param onCompletion The completion handler to call when the NFC scanning operation is complete. Providing any errors that occurred and the NFC scanning result.
///
- (void)performNfcScanWithDocumentNumber:(NSString * _Nonnull)documentNumber dateOfBirth:(NSString * _Nonnull)dateOfBirth dateOfExpiry:(NSString * _Nonnull)dateOfExpiry challenge:(NSArray<NSNumber *> * _Nullable)challenge authenticationType:(NSString * _Nullable)authenticationType onCompletion:(void (^ _Nonnull)(NSError * _Nullable, DaonDocumentProcessorResult * _Nullable))onCompletion;
/// Cancels any ongoing MRZ OCR or NFC scanning operations.
/// \param withMessage The message to provide to the user when cancelling any NFC scanning UI. Or nil if no message is required.
///
- (void)cancelWithMessage:(NSString * _Nullable)withMessage;
/// Internal - Releases any resources held by the document processor module.
/// After calling this method, the module cannot be used again.
- (void)close;
@end

/// The result of a document processor.
SWIFT_CLASS("_TtC12DaonTrustSDK27DaonDocumentProcessorResult")
@interface DaonDocumentProcessorResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum DaonEventCode : NSInteger;
/// Events returned from SDK to the client app.
/// Contains code and localizedDescription
SWIFT_CLASS("_TtC12DaonTrustSDK9DaonEvent")
@interface DaonEvent : NSObject
/// Enum with Int raw value of the <code>DaonEvent</code>
@property (nonatomic, readonly) enum DaonEventCode code;
/// Localized Description of the <code>DaonEvent</code>
@property (nonatomic, readonly, copy) NSString * _Nullable localizedDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Enum with Int raw value of the <code>DaonEvent</code>
/// <blockquote>
/// DaonEventCode structure breakdown:
/// The first pair of digits represents event status. Event status can be: Success (10), Fail (20), Info (30).
/// The second pair of digits represents section of the event. Event sections can be: QR (01), MRZ (02), NFC (03), Web (04), Other (05).
/// The third pair of digits represents ordinal code number for that section.
///
/// </blockquote>
typedef SWIFT_ENUM(NSInteger, DaonEventCode, open) {
/// Returned when Scanned QR code is not valid.
  DaonEventCodeQrScanInvalidQRCode = 200103,
/// Returned when Web session for onboarding process expired.
  DaonEventCodeWebSessionExpired = 200401,
/// Returned when Web application process terminated.
  DaonEventCodeWebAppTerminated = 200402,
/// Returned when Web session for onboarding process completed successfully.
  DaonEventCodeWebSessionCompleted = 100403,
  DaonEventCodeWebAppTimeout = 200403,
/// Returned when Camera permission denied.
  DaonEventCodeCameraPermissionDenied = 200501,
/// Returned when Internet connection not available.
  DaonEventCodeNoInternetConnection = 200502,
/// Returned when current iOS version not supported.
  DaonEventCodeNotSupportediOS = 200503,
/// Returned when DaonTrust SDK client version not compatible with server version.
  DaonEventCodeVersionNotCompatible = 200505,
/// Returned when Provided URL is not whitelisted.
  DaonEventCodeUrlNotWhitelisted = 200508,
/// Returned when webLoaded call has timed out
  DaonEventCodeWebLoadingTimeout = 200509,
/// Returned when SDK was programmatically stopped
  DaonEventCodeSdkProgrammaticallyStopped = 200510,
};

/// Conforming to this delegate, which is required,  a user gets all success, failed and info data from SDK.
SWIFT_PROTOCOL("_TtP12DaonTrustSDK17DaonEventDelegate_")
@protocol DaonEventDelegate
/// Sucess event from SDK
/// \param daonEvent see <code>DaonEvent</code> for more details
///
- (void)didReceiveWithSuccessResponse:(DaonEvent * _Nonnull)daonEvent;
/// Failed event from SDK
/// \param daonEvent see <code>DaonEvent</code> for more details
///
- (void)didReceiveWithFailedResponse:(DaonEvent * _Nonnull)daonEvent;
- (void)didReceiveWithInfoResponse:(DaonEvent * _Nonnull)daonEvent SWIFT_DEPRECATED_MSG("To be removed in the next release");
@end

/// DaonOptions which are used as a configuration of the SDK. If parameters are not set default values will be used.
/// \code
/// let daonOptions = DaonOptions()
/// daonOptions.serverUrl = "https://www.someUrl.com"
/// daonOptions.initializationTimeout = 30
///
/// \endcode\param serverUrl String with default value of empty string
///
/// \param initializationTimeout Int with default value of <code>10</code>
///
SWIFT_CLASS("_TtC12DaonTrustSDK11DaonOptions")
@interface DaonOptions : NSObject
/// Server URL which will be targeted, default is empty string - if empty QR scan screen will be initiated
@property (nonatomic, copy) NSString * _Nonnull serverUrl;
/// Time interval for waiting response from valid URL, default is 10 seconds
@property (nonatomic) NSTimeInterval initializationTimeout;
/// Description label in QR scan screen, if not set label will not be shown
@property (nonatomic, copy) NSString * _Nonnull qrInstructionLabel;
/// Description label under spinner while loading scanned QR, if not set label will not be shown
@property (nonatomic, copy) NSString * _Nonnull spinnerLabel;
/// Web loaded is a safety feature of the <code>TrustSDK</code> onboarding web app that indicates when a valid web page has loaded. By default, this feature is set to true. This feature should be disabled only for development/debug purpose.
@property (nonatomic) BOOL isWebLoadedEnabled;
/// Whitelisting is a safety feature of the <code>TrustSDK</code> onboarding web app that indicates if web page is whitelisted. By default, this feature is set to true. This feature should be disabled only for development/debug purpose.
@property (nonatomic) BOOL isWhitelistingEnabled;
/// The default value is<code> false</code>. Enable this feature for back/forward web actions in the navigation bar. It should be enabled only for development/debugging purposes or if the web app requires web navigation.
@property (nonatomic) BOOL isWebToolbarEnabled;
/// The default value is<code> true</code>. Optional parameter that indicates whether event logging is enabled or not.
@property (nonatomic) BOOL isAnalyticsEnabled;
/// Initilaze <code>DaonOptions</code> with default values
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Input parameters for FIDO operations such as registration, authentication, deregistration, and notification.
SWIFT_CLASS("_TtC12DaonTrustSDK10Parameters")
@interface Parameters : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIViewController;
/// <code>TrustSDK</code> is the main class for initialization, setting up and starting the process of verification. After init, <code>DaonOptions</code> should be set up, with default or custom options. <code>start(withDaonOptions options: )</code> method begins the whole process by sending a user to a QR scan or directly to the web app. The user is also subscribed to <code>DaonEvent</code> through <code>DaonEventDelegate</code>.
/// \code
///
/// ...
/// import TrustSDK
///
/// class MainViewController: UIViewController, DaonEventDelegate {
///
/// ...
///     func startProcess() {
///         let sdk = TrustSDK(withViewController: self, delegate: self)
///
///         let options = DaonOptions()
///         // set up DaonOptions or leave it as default
///
///         sdk.start(withDaonOptions: options)
///     }
/// ...
///
///     // DaonEventDelegate
///     func didReceive(successResponse daonEvent: DaonEvent) {
///         print("Feed triggered, success type, description: \(daonEvent.code), description: \(daonEvent.localizedDescription ?? "")")
///     }
///
///     func didReceive(failedResponse daonEvent: DaonEvent) {
///         print("Feed triggered, failed type, description: \(daonEvent.code), description: \(daonEvent.localizedDescription ?? "")")
///     }
///
///     func didReceive(infoResponse daonEvent: DaonEvent) {
///         print("Feed triggered, info type, description: \(daonEvent.code), description: \(daonEvent.localizedDescription ?? "")")
///     }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC12DaonTrustSDK8TrustSDK")
@interface TrustSDK : NSObject
/// Init method for TrustSDK needed for starting process
/// \param vc parrent view controller
///
/// \param delegate subscribe for <code>DaonEventDelegate</code> methods
///
- (nonnull instancetype)initWithViewController:(UIViewController * _Nonnull)vc delegate:(id <DaonEventDelegate> _Nonnull)delegate OBJC_DESIGNATED_INITIALIZER;
/// Add a document processing module to TrustSDK. Typically this is used for MRZ reading and NFC scanning.
/// \param processor The Document processor to use, typically a <code>DaonDocumentProcessor</code> instance.
///
- (void)addDocumentProcessor:(id <DaonDocumentProcessorModule> _Nonnull)processor;
- (void)addAppkeysProcessor:(id <DaonAppkeysProcessorModule> _Nonnull)processor;
- (void)addDeviceIntegrityProcessor:(id <DaonDeviceIntegrityProcessorModule> _Nonnull)processor;
/// Start verification process
/// \param options Set options if needed, for default values pass <code>DaonOptions</code> object
///
- (void)startWithDaonOptions:(DaonOptions * _Nonnull)options;
/// Stop the SDK process and dismiss any active view controllers
/// This method will terminate the current SDK flow and notify the delegate with a failure response
- (void)stop;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface TrustSDK (SWIFT_EXTENSION(DaonTrustSDK)) <DaonEventDelegate>
- (void)didReceiveWithSuccessResponse:(DaonEvent * _Nonnull)daonEvent;
- (void)didReceiveWithFailedResponse:(DaonEvent * _Nonnull)daonEvent;
- (void)didReceiveWithInfoResponse:(DaonEvent * _Nonnull)daonEvent;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef DAONTRUSTSDK_SWIFT_H
#define DAONTRUSTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DaonTrustSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// A FIDO credential representing a registered authenticator.
/// Example JSON representation:
/// \code
/// {
///   "name": "silent",
///   "aaid": "D409#2601",
///   "keyid": "4c2b3ea0-cc3f-4b60-8588-207fd53608f2",
///   "created": 1751037260645,
///   "username": "jonny"
/// }
///
/// \endcode
SWIFT_CLASS("_TtC12DaonTrustSDK10Credential")
@interface Credential : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Configuration parameters for a device intelligence operation.
SWIFT_CLASS("_TtC12DaonTrustSDK12DIParameters")
@interface DIParameters : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@class Parameters;
/// The <code>DaonAppkeysProcessorModule</code> protocol defines a contract whereby an object that implements it can be used
/// to perform FIDO/UAF authentication, registration, and credential management.
SWIFT_PROTOCOL("_TtP12DaonTrustSDK26DaonAppkeysProcessorModule_")
@protocol DaonAppkeysProcessorModule
/// Returns the FIDO application identifier for the current session.
- (NSString * _Nonnull)appId SWIFT_WARN_UNUSED_RESULT;
/// Returns whether the required FIDO frameworks (DaonFIDOSDK, DaonCryptoSDK, DaonAuthenticatorSDK) are available at runtime.
- (BOOL)isAvailable SWIFT_WARN_UNUSED_RESULT;
/// Returns whether biometric authentication (Touch ID or Face ID) is supported and enabled on this device.
- (BOOL)isBiometricsSupported SWIFT_WARN_UNUSED_RESULT;
/// Returns the version string of the underlying FIDO SDK.
- (NSString * _Nonnull)version SWIFT_WARN_UNUSED_RESULT;
/// Retrieves the list of registered FIDO credentials as a base64-encoded JSON string.
/// \param completion A closure called with the base64-encoded credential JSON on success, or an <code>Error</code> on failure.
///
- (void)credentialsWithCompletion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Performs a FIDO registration operation using the provided parameters.
/// \param parameters A <code>Parameters</code> instance containing the base64-encoded FIDO message and optional configuration.
///
/// \param completion A closure called with the base64-encoded registration response on success, or an <code>Error</code> on failure.
///
- (void)registerWithParameters:(Parameters * _Nonnull)parameters completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Performs a FIDO authentication operation using the provided parameters.
/// \param parameters A <code>Parameters</code> instance containing the base64-encoded FIDO message and optional configuration.
///
/// \param completion A closure called with the base64-encoded authentication response on success, or an <code>Error</code> on failure.
///
- (void)authenticateWithParameters:(Parameters * _Nonnull)parameters completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Deregisters one or more FIDO authenticators.
/// \param parameters A <code>Parameters</code> instance containing a base64-encoded FIDO deregistration message, or a name such as <code>"ALL"</code>, <code>"BIOMETRIC"</code>, or <code>"DEVICE"</code>.
///
/// \param completion A closure called with the base64-encoded result on success, or an <code>Error</code> on failure.
///
- (void)deregisterWithParameters:(Parameters * _Nonnull)parameters completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Sends a FIDO notification with the provided parameters.
/// \param parameters A <code>Parameters</code> instance containing the base64-encoded FIDO notification message.
///
/// \param completion A closure called with the base64-encoded result on success, or an <code>Error</code> on failure.
///
- (void)notifyWithParameters:(Parameters * _Nonnull)parameters completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Cancels any ongoing operations.
/// \param message The message to provide to the user when cancelling any NFC scanning UI. Or nil if no message is required.
///
- (void)cancelWithMessage:(NSString * _Nullable)message;
/// Releases any resources held by the processor module.
/// After calling this method, the module cannot be used again.
- (void)close;
@end

/// The <code>DaonDeviceIntegrityProcessorModule</code> protocol defines a contract for performing
/// device intelligence operations using a device fingerprinting service.
SWIFT_PROTOCOL("_TtP12DaonTrustSDK34DaonDeviceIntegrityProcessorModule_")
@protocol DaonDeviceIntegrityProcessorModule
/// Returns whether the device intelligence framework is available at runtime.
///
/// returns:
/// <code>true</code> if the required framework is linked and loaded; otherwise <code>false</code>.
- (BOOL)isAvailable SWIFT_WARN_UNUSED_RESULT;
/// Returns the version string of the underlying device intelligence SDK.
- (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
/// Returns the list of supported capability identifiers (e.g. <code>"SIGNALS"</code>).
- (NSArray<NSString *> * _Nonnull)getCapabilities SWIFT_WARN_UNUSED_RESULT;
/// Performs a device fingerprint operation and returns the result asynchronously.
/// \param parameters A <code>DIParameters</code> instance containing the API key, region, and optional endpoint.
///
/// \param completion A closure called with a base64-encoded sealed result on success, or an <code>Error</code> on failure.
///
- (void)processOperationWithParameters:(DIParameters * _Nonnull)parameters completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Releases any resources held by the processor. The module should not be used after calling this method.
- (void)close;
@end

@class DaonDocumentProcessorResult;
/// The <code>DaonDocumentProcessorModule</code> protocol defines a contract whereby an object that implements it can be used to perform
/// MRZ Image OCR and NFC Scanning.
SWIFT_PROTOCOL("_TtP12DaonTrustSDK27DaonDocumentProcessorModule_")
@protocol DaonDocumentProcessorModule
/// Determines whether NFC scanning is supported with the current device and operating system configuration.
///
/// returns:
/// <code>true</code> if NFC scanning is supported, <code>false</code> otherwise.
- (BOOL)isNfcSupported SWIFT_WARN_UNUSED_RESULT;
/// Performs MRZ OCR on the provided image.
/// \param image The base64 encoded image to perform MRZ OCR on.
///
/// \param onCompletion The completion handler to call when the MRZ OCR operation is complete. Providing whether the MRZ is valid and the MRZ string.
///
- (void)performMrzOcrWithImage:(NSString * _Nonnull)base64String onCompletion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))onCompletion;
/// Performs NFC scanning using the provided mrz string.
/// \param mrzString The MRZ string to be used for BAC or PACE access control.
///
/// \param challenge The challenge to use for NFC scanning. Or nil if no challenge is required.
///
/// \param authenticationType The authentication type to use with the NFC document. Or nil if the default (BAC then PACE) is acceptable.
///
/// \param onCompletion The completion handler to call when the NFC scanning operation is complete. Providing any errors that occurred and the NFC scanning result.
///
- (void)performNfcScanWithMrzString:(NSString * _Nonnull)mrzString challenge:(NSArray<NSNumber *> * _Nullable)challenge authenticationType:(NSString * _Nullable)authenticationType onCompletion:(void (^ _Nonnull)(NSError * _Nullable, DaonDocumentProcessorResult * _Nullable))onCompletion;
/// Performs NFC scanning using the provided bac access control parameters.
/// \param docummentNumber BAC document number.
///
/// \param dateOfBirth BAC document date of birth. Using the “yyMMdd” format.
///
/// \param dateOfExpiry BAC document date of expiration. Using the “yyMMdd” format.
///
/// \param challenge The challenge to use for NFC scanning. Or nil if no challenge is required.
///
/// \param authenticationType The authentication type to use with the NFC document. Or nil if the default (BAC then PACE) is acceptable.
///
/// \param onCompletion The completion handler to call when the NFC scanning operation is complete. Providing any errors that occurred and the NFC scanning result.
///
- (void)performNfcScanWithDocumentNumber:(NSString * _Nonnull)documentNumber dateOfBirth:(NSString * _Nonnull)dateOfBirth dateOfExpiry:(NSString * _Nonnull)dateOfExpiry challenge:(NSArray<NSNumber *> * _Nullable)challenge authenticationType:(NSString * _Nullable)authenticationType onCompletion:(void (^ _Nonnull)(NSError * _Nullable, DaonDocumentProcessorResult * _Nullable))onCompletion;
/// Cancels any ongoing MRZ OCR or NFC scanning operations.
/// \param withMessage The message to provide to the user when cancelling any NFC scanning UI. Or nil if no message is required.
///
- (void)cancelWithMessage:(NSString * _Nullable)withMessage;
/// Internal - Releases any resources held by the document processor module.
/// After calling this method, the module cannot be used again.
- (void)close;
@end

/// The result of a document processor.
SWIFT_CLASS("_TtC12DaonTrustSDK27DaonDocumentProcessorResult")
@interface DaonDocumentProcessorResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum DaonEventCode : NSInteger;
/// Events returned from SDK to the client app.
/// Contains code and localizedDescription
SWIFT_CLASS("_TtC12DaonTrustSDK9DaonEvent")
@interface DaonEvent : NSObject
/// Enum with Int raw value of the <code>DaonEvent</code>
@property (nonatomic, readonly) enum DaonEventCode code;
/// Localized Description of the <code>DaonEvent</code>
@property (nonatomic, readonly, copy) NSString * _Nullable localizedDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Enum with Int raw value of the <code>DaonEvent</code>
/// <blockquote>
/// DaonEventCode structure breakdown:
/// The first pair of digits represents event status. Event status can be: Success (10), Fail (20), Info (30).
/// The second pair of digits represents section of the event. Event sections can be: QR (01), MRZ (02), NFC (03), Web (04), Other (05).
/// The third pair of digits represents ordinal code number for that section.
///
/// </blockquote>
typedef SWIFT_ENUM(NSInteger, DaonEventCode, open) {
/// Returned when Scanned QR code is not valid.
  DaonEventCodeQrScanInvalidQRCode = 200103,
/// Returned when Web session for onboarding process expired.
  DaonEventCodeWebSessionExpired = 200401,
/// Returned when Web application process terminated.
  DaonEventCodeWebAppTerminated = 200402,
/// Returned when Web session for onboarding process completed successfully.
  DaonEventCodeWebSessionCompleted = 100403,
  DaonEventCodeWebAppTimeout = 200403,
/// Returned when Camera permission denied.
  DaonEventCodeCameraPermissionDenied = 200501,
/// Returned when Internet connection not available.
  DaonEventCodeNoInternetConnection = 200502,
/// Returned when current iOS version not supported.
  DaonEventCodeNotSupportediOS = 200503,
/// Returned when DaonTrust SDK client version not compatible with server version.
  DaonEventCodeVersionNotCompatible = 200505,
/// Returned when Provided URL is not whitelisted.
  DaonEventCodeUrlNotWhitelisted = 200508,
/// Returned when webLoaded call has timed out
  DaonEventCodeWebLoadingTimeout = 200509,
/// Returned when SDK was programmatically stopped
  DaonEventCodeSdkProgrammaticallyStopped = 200510,
};

/// Conforming to this delegate, which is required,  a user gets all success, failed and info data from SDK.
SWIFT_PROTOCOL("_TtP12DaonTrustSDK17DaonEventDelegate_")
@protocol DaonEventDelegate
/// Sucess event from SDK
/// \param daonEvent see <code>DaonEvent</code> for more details
///
- (void)didReceiveWithSuccessResponse:(DaonEvent * _Nonnull)daonEvent;
/// Failed event from SDK
/// \param daonEvent see <code>DaonEvent</code> for more details
///
- (void)didReceiveWithFailedResponse:(DaonEvent * _Nonnull)daonEvent;
- (void)didReceiveWithInfoResponse:(DaonEvent * _Nonnull)daonEvent SWIFT_DEPRECATED_MSG("To be removed in the next release");
@end

/// DaonOptions which are used as a configuration of the SDK. If parameters are not set default values will be used.
/// \code
/// let daonOptions = DaonOptions()
/// daonOptions.serverUrl = "https://www.someUrl.com"
/// daonOptions.initializationTimeout = 30
///
/// \endcode\param serverUrl String with default value of empty string
///
/// \param initializationTimeout Int with default value of <code>10</code>
///
SWIFT_CLASS("_TtC12DaonTrustSDK11DaonOptions")
@interface DaonOptions : NSObject
/// Server URL which will be targeted, default is empty string - if empty QR scan screen will be initiated
@property (nonatomic, copy) NSString * _Nonnull serverUrl;
/// Time interval for waiting response from valid URL, default is 10 seconds
@property (nonatomic) NSTimeInterval initializationTimeout;
/// Description label in QR scan screen, if not set label will not be shown
@property (nonatomic, copy) NSString * _Nonnull qrInstructionLabel;
/// Description label under spinner while loading scanned QR, if not set label will not be shown
@property (nonatomic, copy) NSString * _Nonnull spinnerLabel;
/// Web loaded is a safety feature of the <code>TrustSDK</code> onboarding web app that indicates when a valid web page has loaded. By default, this feature is set to true. This feature should be disabled only for development/debug purpose.
@property (nonatomic) BOOL isWebLoadedEnabled;
/// Whitelisting is a safety feature of the <code>TrustSDK</code> onboarding web app that indicates if web page is whitelisted. By default, this feature is set to true. This feature should be disabled only for development/debug purpose.
@property (nonatomic) BOOL isWhitelistingEnabled;
/// The default value is<code> false</code>. Enable this feature for back/forward web actions in the navigation bar. It should be enabled only for development/debugging purposes or if the web app requires web navigation.
@property (nonatomic) BOOL isWebToolbarEnabled;
/// The default value is<code> true</code>. Optional parameter that indicates whether event logging is enabled or not.
@property (nonatomic) BOOL isAnalyticsEnabled;
/// Initilaze <code>DaonOptions</code> with default values
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Input parameters for FIDO operations such as registration, authentication, deregistration, and notification.
SWIFT_CLASS("_TtC12DaonTrustSDK10Parameters")
@interface Parameters : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIViewController;
/// <code>TrustSDK</code> is the main class for initialization, setting up and starting the process of verification. After init, <code>DaonOptions</code> should be set up, with default or custom options. <code>start(withDaonOptions options: )</code> method begins the whole process by sending a user to a QR scan or directly to the web app. The user is also subscribed to <code>DaonEvent</code> through <code>DaonEventDelegate</code>.
/// \code
///
/// ...
/// import TrustSDK
///
/// class MainViewController: UIViewController, DaonEventDelegate {
///
/// ...
///     func startProcess() {
///         let sdk = TrustSDK(withViewController: self, delegate: self)
///
///         let options = DaonOptions()
///         // set up DaonOptions or leave it as default
///
///         sdk.start(withDaonOptions: options)
///     }
/// ...
///
///     // DaonEventDelegate
///     func didReceive(successResponse daonEvent: DaonEvent) {
///         print("Feed triggered, success type, description: \(daonEvent.code), description: \(daonEvent.localizedDescription ?? "")")
///     }
///
///     func didReceive(failedResponse daonEvent: DaonEvent) {
///         print("Feed triggered, failed type, description: \(daonEvent.code), description: \(daonEvent.localizedDescription ?? "")")
///     }
///
///     func didReceive(infoResponse daonEvent: DaonEvent) {
///         print("Feed triggered, info type, description: \(daonEvent.code), description: \(daonEvent.localizedDescription ?? "")")
///     }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC12DaonTrustSDK8TrustSDK")
@interface TrustSDK : NSObject
/// Init method for TrustSDK needed for starting process
/// \param vc parrent view controller
///
/// \param delegate subscribe for <code>DaonEventDelegate</code> methods
///
- (nonnull instancetype)initWithViewController:(UIViewController * _Nonnull)vc delegate:(id <DaonEventDelegate> _Nonnull)delegate OBJC_DESIGNATED_INITIALIZER;
/// Add a document processing module to TrustSDK. Typically this is used for MRZ reading and NFC scanning.
/// \param processor The Document processor to use, typically a <code>DaonDocumentProcessor</code> instance.
///
- (void)addDocumentProcessor:(id <DaonDocumentProcessorModule> _Nonnull)processor;
- (void)addAppkeysProcessor:(id <DaonAppkeysProcessorModule> _Nonnull)processor;
- (void)addDeviceIntegrityProcessor:(id <DaonDeviceIntegrityProcessorModule> _Nonnull)processor;
/// Start verification process
/// \param options Set options if needed, for default values pass <code>DaonOptions</code> object
///
- (void)startWithDaonOptions:(DaonOptions * _Nonnull)options;
/// Stop the SDK process and dismiss any active view controllers
/// This method will terminate the current SDK flow and notify the delegate with a failure response
- (void)stop;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface TrustSDK (SWIFT_EXTENSION(DaonTrustSDK)) <DaonEventDelegate>
- (void)didReceiveWithSuccessResponse:(DaonEvent * _Nonnull)daonEvent;
- (void)didReceiveWithFailedResponse:(DaonEvent * _Nonnull)daonEvent;
- (void)didReceiveWithInfoResponse:(DaonEvent * _Nonnull)daonEvent;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
